name: Deploy to Azure Web App

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Log in to Azure Container Registry
      run: echo ${{ secrets.ACR_PASSWORD }} | docker login legislatordashboardsacr.azurecr.io --username ${{ secrets.ACR_USERNAME }} --password-stdin

    - name: Build and push Docker image
      run: |
        docker build . -t legislatordashboardsacr.azurecr.io/legislatordashboard:latest
        docker push legislatordashboardsacr.azurecr.io/legislatordashboard:latest
